# fly.toml app configuration file generated for tomhuibregtse-aged-bush-4781 on 2024-04-07T08:45:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tomhuibregtse'
primary_region = 'ord'
console_command = '/code/manage.py shell'

[build]

[env]
  DEBUG = 'False'
  EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
  EMAIL_HOST = 'smtp.gmail.com'
  EMAIL_PORT = '587'
  EMAIL_USE_SSL = 'False'
  EMAIL_USE_TLS = 'True'
  PORT = '8000'
  DATABASE_PATH = "/data/db.sqlite3"
  STATIC_ROOT = "/data/staticfiles"

[[mounts]]
  source = 'tomhuibregtse_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
