# Generated by Django 5.0.4 on 2024-04-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="title",
            field=models.CharField(default="title", max_length=255),
            preserve_default=False,
        ),
    ]
