# Generated by Django 5.0.4 on 2024-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
